[tools]
bun = "1.2.22"

[settings]
experimental = true
pin = true

[hooks]
postinstall = "bun install"

[env]
_.path = "node_modules/.bin"

[tasks.start]
run = "bun game"
raw = true
depends = ["build"]

[tasks.build]
run = "tsc"

[tasks.dev]
run = "bun --watch game"
raw = true

[tasks.prepack]
run = "bun build"

[tasks.release]
run = "bunx auto shipit"
